// Weapon stats for the arsenal. Times are in seconds.
// `key` is the keyboard binding shown in the HUD (digits for the first ten guns,
// letters for the rest, "V" for the blade). `sound` maps to a profile in
// AudioManager.playShot(). The scroll wheel cycles through everything.
const WEAPON_DEFINITIONS = [
  {
    id: 'sidearm',
    name: 'Pulse Pistol',
    key: '1',
    kind: 'hitscan',
    sound: 'sidearm',
    damage: 51,             // 2-shot body kill (100 HP / 51 ≈ 2 shots)
    headshotMultiplier: 2.0, // 1-shot headshot kill
    pellets: 1,
    spread: 0.004,
    fireRate: 0.55,
    automatic: false,
    magSize: 6,
    reserveMax: 36,
    reloadTime: 1.4,
    range: 140,
    recoil: 0.035,
    color: 0x061a2a
  },
  {
    id: 'uzi',
    name: 'Scatter Blaster',
    key: '2',
    kind: 'hitscan',
    sound: 'smg',
    damage: 12,
    pellets: 1,
    spread: 0.02,
    fireRate: 0.07,
    automatic: true,
    magSize: 32,
    reserveMax: 160,
    reloadTime: 1.5,
    range: 80,
    recoil: 0.013,
    color: 0x0c1520
  },
  {
    id: 'levershotgun',
    name: 'Volt Cannon',
    key: '3',
    kind: 'hitscan',
    sound: 'shotgun',
    damage: 10,
    pellets: 8,
    spread: 0.085,
    fireRate: 0.7,
    automatic: false,
    magSize: 6,
    reserveMax: 30,
    reloadTime: 2.0,
    range: 30,
    recoil: 0.05,
    color: 0x1a0e2e
  },
  {
    id: 'm4',
    name: 'AR-9 Assault',
    key: '4',
    kind: 'hitscan',
    sound: 'rifle',
    damage: 22,
    pellets: 1,
    spread: 0.009,
    fireRate: 0.1,
    automatic: true,
    magSize: 30,
    reserveMax: 120,
    reloadTime: 1.8,
    range: 150,
    recoil: 0.02,
    color: 0x394049,
    energyColor: 0x2ee6ff,
    sciFi: true
  },
  {
    id: 'm16',
    name: 'Ion Repeater',
    key: '5',
    kind: 'hitscan',
    sound: 'rifle',
    damage: 24,
    pellets: 1,
    spread: 0.009,
    fireRate: 0.1,
    automatic: true,
    magSize: 20,
    reserveMax: 120,
    reloadTime: 2.0,
    range: 160,
    recoil: 0.02,
    color: 0x080e1a
  },
  {
    id: 'rifle',
    name: 'Comet Rifle',
    key: '6',
    kind: 'hitscan',
    sound: 'rifle',
    damage: 24,
    pellets: 1,
    spread: 0.01,
    fireRate: 0.13,
    automatic: true,
    magSize: 28,
    reserveMax: 112,
    reloadTime: 1.9,
    range: 140,
    recoil: 0.022,
    color: 0x0f1a14
  },
  {
    id: 'lmg',
    name: 'Plasma Suppressor',
    key: 'H',
    kind: 'hitscan',
    sound: 'lmg',
    damage: 20,
    pellets: 1,
    spread: 0.022,
    fireRate: 0.09,
    automatic: true,
    magSize: 100,
    reserveMax: 200,
    reloadTime: 4.5,
    range: 160,
    recoil: 0.03,
    color: 0x0a1018
  },
  {
    id: 'rpg',
    name: 'Nova Launcher',
    key: 'G',
    kind: 'rocket',
    sound: 'rpg',
    damage: 130,
    splashRadius: 5.5,
    splashMin: 0.25,
    rocketSpeed: 40,
    pellets: 1,
    spread: 0,
    fireRate: 1.2,
    automatic: false,
    magSize: 1,
    reserveMax: 6,
    reloadTime: 3.2,
    range: 220,
    recoil: 0.09,
    color: 0x180a22
  },
  {
    id: 'boltsniper',
    name: 'Rail Driver',
    key: 'B',
    kind: 'hitscan',
    sound: 'sniper',
    damage: 110,
    pellets: 1,
    spread: 0.0008,
    fireRate: 1.4,
    automatic: false,
    magSize: 5,
    reserveMax: 25,
    reloadTime: 2.8,
    range: 320,
    recoil: 0.06,
    scoped: true,
    color: 0x050e20
  },
  {
    id: 'knife',
    name: 'Plasma Blade',
    key: 'C',
    kind: 'melee',
    damage: 55,            // melee stab damage
    fireRate: 0.32,
    range: 2.2,
    arc: 0.9,
    throwable: true,
    throwSpeed: 42,
    throwDamage: 9999,     // one-hit kill on throw
    throwCooldown: 0.85,   // seconds before you pull a fresh knife
    throwRewardMult: 3,    // 3x coins/score/xp — only on a thrown kill
    color: 0x00aaff
  },
  {
    id: 'sword',
    name: 'Arc Blade',
    key: 'V',
    kind: 'melee',
    damage: 65,
    fireRate: 0.45,
    range: 2.6,
    arc: 1.0,
    color: 0x00e5ff
  },
  // ── Halo/Destiny-style expanded arsenal ──────────────────────────────────
  {
    id: 'magnum',
    name: 'M6 Magnum',
    key: '7',
    kind: 'hitscan',
    sound: 'sidearm',
    damage: 38,
    headshotMultiplier: 2.2,
    pellets: 1,
    spread: 0.003,
    fireRate: 0.28,
    automatic: false,
    magSize: 8,
    reserveMax: 48,
    reloadTime: 1.2,
    range: 120,
    recoil: 0.028,
    color: 0x394049,
    energyColor: 0x2ee6ff,
    sciFi: true
  },
  {
    id: 'battlerifle',
    name: 'Battle Rifle',
    key: '8',
    kind: 'hitscan',
    sound: 'rifle',
    damage: 22,
    headshotMultiplier: 1.8,
    pellets: 3,
    spread: 0.008,
    fireRate: 0.45,
    automatic: false,
    magSize: 36,
    reserveMax: 108,
    reloadTime: 2.0,
    range: 170,
    recoil: 0.022,
    color: 0x394049,
    energyColor: 0x2ee6ff,
    sciFi: true
  },
  {
    id: 'needler',
    name: 'Needler',
    key: '9',
    kind: 'hitscan',
    sound: 'smg',
    damage: 7,
    pellets: 1,
    spread: 0.04,
    fireRate: 0.06,
    automatic: true,
    magSize: 22,
    reserveMax: 110,
    reloadTime: 1.8,
    range: 55,
    recoil: 0.01,
    color: 0x6600aa
  },
  {
    id: 'plasmarifle',
    name: 'Plasma Rifle',
    key: '0',
    kind: 'hitscan',
    sound: 'smg',
    damage: 13,
    pellets: 1,
    spread: 0.015,
    fireRate: 0.08,
    automatic: true,
    magSize: 40,
    reserveMax: 160,
    reloadTime: 1.6,
    range: 90,
    recoil: 0.014,
    color: 0x394049,
    energyColor: 0x2ee6ff,
    sciFi: true
  },
  {
    id: 'dmr',
    name: 'DMR',
    key: 'R',
    kind: 'hitscan',
    sound: 'rifle',
    damage: 30,
    headshotMultiplier: 2.0,
    pellets: 1,
    spread: 0.004,
    fireRate: 0.32,
    automatic: false,
    magSize: 15,
    reserveMax: 75,
    reloadTime: 2.2,
    range: 200,
    recoil: 0.028,
    color: 0x0a1a10
  },
  {
    id: 'fuelrod',
    name: 'Fuel Rod',
    key: 'T',
    kind: 'rocket',
    sound: 'rpg',
    damage: 100,
    splashRadius: 4.5,
    splashMin: 0.2,
    rocketSpeed: 28,
    pellets: 1,
    spread: 0,
    fireRate: 1.6,
    automatic: false,
    magSize: 1,
    reserveMax: 5,
    reloadTime: 3.5,
    range: 180,
    recoil: 0.12,
    color: 0x002200
  },
  {
    id: 'concussion',
    name: 'Concussion Rifle',
    key: 'Y',
    kind: 'rocket',
    sound: 'rpg',
    damage: 55,
    splashRadius: 3.0,
    splashMin: 0.3,
    rocketSpeed: 35,
    pellets: 1,
    spread: 0,
    fireRate: 0.9,
    automatic: false,
    magSize: 6,
    reserveMax: 24,
    reloadTime: 2.5,
    range: 150,
    recoil: 0.06,
    color: 0x0a1a2a
  },
  {
    id: 'energyshotgun',
    name: 'Scattershot',
    key: 'U',
    kind: 'hitscan',
    sound: 'shotgun',
    damage: 12,
    pellets: 10,
    spread: 0.095,
    fireRate: 0.65,
    automatic: false,
    magSize: 8,
    reserveMax: 40,
    reloadTime: 1.8,
    range: 28,
    recoil: 0.055,
    color: 0x394049,
    energyColor: 0x2ee6ff,
    sciFi: true
  },
  {
    id: 'ghammer',
    name: 'Gravity Hammer',
    key: 'X',
    kind: 'melee',
    damage: 120,
    fireRate: 0.85,
    range: 3.2,
    arc: 1.4,
    color: 0x1a0a00
  },
];

function defaultHeadshotMultiplier(definition) {
  if (definition.kind !== 'hitscan') return undefined;
  if (definition.sound === 'shotgun') return 1.25;
  if (definition.sound === 'sniper') return 2.0;
  return 1.75;
}

/**
 * Every local hitscan family has an explicit headshot balance. Individually
 * authored values above remain authoritative (for example, the Pulse Pistol's
 * deliberate one-shot headshot); missing values use a 1.75x baseline, with a
 * restrained 1.25x per-pellet shotgun bonus and a 2.0x precision-rifle bonus.
 */
export const WEAPONS = WEAPON_DEFINITIONS.map((definition) => {
  const headshotMultiplier = definition.headshotMultiplier
    ?? defaultHeadshotMultiplier(definition);
  return Object.freeze(headshotMultiplier === undefined
    ? { ...definition }
    : { ...definition, headshotMultiplier });
});

export function getWeapon(id) {
  return WEAPONS.find((w) => w.id === id);
}
